# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 自己紹介
email: your-email@example.com
locale: "ja-JP" # 日本語設定
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# Remote Theme の設定
remote_theme: "mmistakes/minimal-mistakes@4.24.0" # 最新バージョンを指定
baseurl: "/portfolio-jekyll" # the subpath of your site, e.g. /blog
url: "https://pokeyama.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MochiyamaTarou
github_username:  Pokeyama

# Build settings
# theme: minima
# プラグインの設定
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-seo-tag


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
sass:
  quiet_deps: true
  style: compressed
  load_paths:
    - assets/css

# ナビゲーションメニューの設定
navigation:
  - nav:
      links:
        - title: "プロフィール"
          url: "/"
        - title: "スキル"
          url: "/skill/"
        - title: "経験プロジェクト"
          url: "/experience/"
        - title: "自己PR"
          url: "/self/"

# theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "mint" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

author:
  name: "平山 勇太朗"
  avatar: "/assets/IMG_0760.JPG"
  bio: "どうせ転職活動をするならと自己紹介ページを作ってみました。" # Note: Markdown is allowed
  # location: "Somewhere"
  links:
    - label: " Qiita"
      icon: "fas fa-pen" # 代替アイコンとしてペンを使用
      url: "https://qiita.com/simoyama2323"
    - label: "X"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/MochiyamaTarou"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Pokeyama"
    - label: " mail"
      icon: "fas fa-envelope"
      url: "https://github.com/Pokeyama"